import type { AccessPoint, Band, Encryption, PmfMode, Station } from "./types";

export interface ApTemplate {
  ssid: string;
  bssid: string;
  vendor: string;
  band: Band;
  channel: number;
  widthMhz: number;
  encryption: Encryption;
  cipher: string;
  akm: string;
  pmf: PmfMode;
  wps: boolean;
  hidden: boolean;
  txPowerDbm: number;
  position: { x: number; y: number };
  role: string;
  notes: string;
  psk?: string;
  pmkidExposed: boolean;
  rogue: boolean;
}

export interface StaTemplate {
  mac: string;
  manufacturer: string;
  associatedBssid: string | null;
  probes: string[];
  position: { x: number; y: number };
}

export const HOPPER_OUI = "00:1A:8C";
export const CAMPUS = { width: 120, height: 80 };

export const LAB_APS: ApTemplate[] = [
  {
    ssid: "Hopper-Corp",
    bssid: "00:1A:8C:10:00:01",
    vendor: "Hopper Networks",
    band: "5",
    channel: 36,
    widthMhz: 80,
    encryption: "WPA3-ENT",
    cipher: "GCMP-256",
    akm: "00-0F-AC:18 (Suite-B 192)",
    pmf: "required",
    wps: false,
    hidden: false,
    txPowerDbm: 20,
    position: { x: 58, y: 22 },
    role: "corp-core",
    notes: "WPA3-Enterprise with 802.11w required. Certificate-based EAP-TLS.",
    pmkidExposed: false,
    rogue: false,
  },
  {
    ssid: "Hopper-Corp",
    bssid: "00:1A:8C:10:00:02",
    vendor: "Hopper Networks",
    band: "2.4",
    channel: 6,
    widthMhz: 20,
    encryption: "WPA2-ENT",
    cipher: "CCMP",
    akm: "00-0F-AC:01 (802.1X)",
    pmf: "optional",
    wps: false,
    hidden: false,
    txPowerDbm: 17,
    position: { x: 62, y: 24 },
    role: "corp-legacy",
    notes: "Transition radio: WPA2-Enterprise, PMF optional. Downgrade path for older clients.",
    pmkidExposed: false,
    rogue: false,
  },
  {
    ssid: "Hopper-Corp-6E",
    bssid: "00:1A:8C:10:00:03",
    vendor: "Hopper Networks",
    band: "6",
    channel: 37,
    widthMhz: 160,
    encryption: "WPA3-ENT",
    cipher: "GCMP-256",
    akm: "00-0F-AC:18",
    pmf: "required",
    wps: false,
    hidden: false,
    txPowerDbm: 18,
    position: { x: 55, y: 20 },
    role: "corp-6e",
    notes: "6 GHz WPA3-Enterprise only. No transition mode.",
    pmkidExposed: false,
    rogue: false,
  },
  {
    ssid: "Hopper-Guest",
    bssid: "00:1A:8C:10:00:10",
    vendor: "Hopper Networks",
    band: "2.4",
    channel: 1,
    widthMhz: 20,
    encryption: "WPA2-PSK",
    cipher: "CCMP",
    akm: "00-0F-AC:02 (PSK)",
    pmf: "off",
    wps: false,
    hidden: false,
    txPowerDbm: 18,
    position: { x: 48, y: 50 },
    role: "guest",
    notes: "Guest PSK, PMF off, PMKID in EAPOL M1. Client isolation unconfirmed.",
    psk: "Welcome1",
    pmkidExposed: true,
    rogue: false,
  },
  {
    ssid: "Hopper-Guest",
    bssid: "00:1A:8C:10:00:11",
    vendor: "Hopper Networks",
    band: "5",
    channel: 44,
    widthMhz: 40,
    encryption: "WPA2-PSK",
    cipher: "CCMP",
    akm: "00-0F-AC:02 (PSK)",
    pmf: "off",
    wps: false,
    hidden: false,
    txPowerDbm: 20,
    position: { x: 50, y: 48 },
    role: "guest",
    notes: "Same PSK as 2.4 GHz guest radio.",
    psk: "Welcome1",
    pmkidExposed: true,
    rogue: false,
  },
  {
    ssid: "Hopper-IoT",
    bssid: "00:1A:8C:10:00:20",
    vendor: "Hopper Networks",
    band: "2.4",
    channel: 11,
    widthMhz: 20,
    encryption: "WPA2-PSK",
    cipher: "CCMP",
    akm: "00-0F-AC:02 (PSK)",
    pmf: "off",
    wps: true,
    hidden: false,
    txPowerDbm: 14,
    position: { x: 88, y: 18 },
    role: "iot",
    notes: "WPS enabled on IoT VLAN. Weak PSK likely. No 802.11w.",
    psk: "sensornet",
    pmkidExposed: true,
    rogue: false,
  },
  {
    ssid: "Hopper-Voice",
    bssid: "00:1A:8C:10:00:30",
    vendor: "Hopper Networks",
    band: "5",
    channel: 149,
    widthMhz: 20,
    encryption: "WPA2-PSK",
    cipher: "CCMP",
    akm: "00-0F-AC:02 (PSK)",
    pmf: "optional",
    wps: false,
    hidden: false,
    txPowerDbm: 16,
    position: { x: 30, y: 18 },
    role: "voice",
    notes: "VoIP SSID. High-entropy PSK. QoS WMM voice.",
    psk: "9f#Kx!2mQpL8vN",
    pmkidExposed: true,
    rogue: false,
  },
  {
    ssid: "Hopper-Mgmt",
    bssid: "00:1A:8C:10:00:40",
    vendor: "Hopper Networks",
    band: "5",
    channel: 40,
    widthMhz: 20,
    encryption: "WPA2-PSK",
    cipher: "CCMP",
    akm: "00-0F-AC:02 (PSK)",
    pmf: "off",
    wps: false,
    hidden: true,
    txPowerDbm: 8,
    position: { x: 60, y: 16 },
    role: "mgmt",
    notes: "Hidden infrastructure SSID. Low TX power. Default-style PSK.",
    psk: "ChangeMe!",
    pmkidExposed: true,
    rogue: false,
  },
  {
    ssid: "Hopper-Corp",
    bssid: "DE:AD:BE:EF:10:01",
    vendor: "Unknown (clone)",
    band: "2.4",
    channel: 6,
    widthMhz: 20,
    encryption: "OPEN",
    cipher: "none",
    akm: "none",
    pmf: "off",
    wps: false,
    hidden: false,
    txPowerDbm: 20,
    position: { x: 64, y: 52 },
    role: "rogue",
    notes: "Evil twin: clones Hopper-Corp SSID, open authentication, non-Hopper OUI.",
    pmkidExposed: false,
    rogue: true,
  },
  {
    ssid: "CivicFree",
    bssid: "3C:7A:8A:22:10:01",
    vendor: "Cisco-Linksys",
    band: "2.4",
    channel: 6,
    widthMhz: 20,
    encryption: "OPEN",
    cipher: "none",
    akm: "none",
    pmf: "off",
    wps: false,
    hidden: false,
    txPowerDbm: 16,
    position: { x: 12, y: 70 },
    role: "neighbor",
    notes: "Municipal open network. Out of lab scope unless explicitly added.",
    pmkidExposed: false,
    rogue: false,
  },
  {
    ssid: "xfinitywifi",
    bssid: "98:F7:D7:44:90:12",
    vendor: "Comcast",
    band: "2.4",
    channel: 11,
    widthMhz: 20,
    encryption: "OPEN",
    cipher: "none",
    akm: "none",
    pmf: "off",
    wps: false,
    hidden: false,
    txPowerDbm: 15,
    position: { x: 110, y: 60 },
    role: "neighbor",
    notes: "MSO hotspot.",
    pmkidExposed: false,
    rogue: false,
  },
  {
    ssid: "NETGEAR70",
    bssid: "A0:04:60:1B:33:70",
    vendor: "Netgear",
    band: "2.4",
    channel: 8,
    widthMhz: 20,
    encryption: "WPA2-PSK",
    cipher: "CCMP",
    akm: "00-0F-AC:02 (PSK)",
    pmf: "off",
    wps: true,
    hidden: false,
    txPowerDbm: 18,
    position: { x: 18, y: 40 },
    role: "neighbor",
    notes: "SOHO AP with WPS and factory-grade PSK.",
    psk: "password",
    pmkidExposed: true,
    rogue: false,
  },
  {
    ssid: "TP-Link_2.4GHz",
    bssid: "50:C7:BF:08:21:AA",
    vendor: "TP-Link",
    band: "2.4",
    channel: 3,
    widthMhz: 20,
    encryption: "WPA-TKIP",
    cipher: "TKIP",
    akm: "00-0F-AC:02 (PSK)",
    pmf: "off",
    wps: true,
    hidden: false,
    txPowerDbm: 17,
    position: { x: 100, y: 30 },
    role: "neighbor",
    notes: "Deprecated TKIP. Immediate protocol finding if brought in-scope.",
    psk: "admin1234",
    pmkidExposed: false,
    rogue: false,
  },
  {
    ssid: "Printer-Setup",
    bssid: "00:1B:A9:77:02:19",
    vendor: "Brother",
    band: "2.4",
    channel: 1,
    widthMhz: 20,
    encryption: "WEP",
    cipher: "WEP-40",
    akm: "none",
    pmf: "off",
    wps: false,
    hidden: false,
    txPowerDbm: 10,
    position: { x: 72, y: 28 },
    role: "iot-legacy",
    notes: "WEP leftover on a printer. Critical if in-scope.",
    psk: "12345678",
    pmkidExposed: false,
    rogue: false,
  },
  {
    ssid: "Marriott_Guest",
    bssid: "00:1E:13:90:44:02",
    vendor: "Aruba",
    band: "5",
    channel: 36,
    widthMhz: 40,
    encryption: "WPA2-PSK",
    cipher: "CCMP",
    akm: "00-0F-AC:02 (PSK)",
    pmf: "optional",
    wps: false,
    hidden: false,
    txPowerDbm: 19,
    position: { x: 8, y: 8 },
    role: "neighbor",
    notes: "Adjacent hospitality SSID.",
    psk: "marriott1",
    pmkidExposed: true,
    rogue: false,
  },
  {
    ssid: "James iPhone",
    bssid: "F2:11:4C:88:03:91",
    vendor: "Apple",
    band: "5",
    channel: 44,
    widthMhz: 80,
    encryption: "WPA2-PSK",
    cipher: "CCMP",
    akm: "00-0F-AC:02 (PSK)",
    pmf: "required",
    wps: false,
    hidden: false,
    txPowerDbm: 12,
    position: { x: 66, y: 44 },
    role: "personal",
    notes: "Personal hotspot. Randomized BSSID.",
    psk: "7hQ!m2Vx9Lp",
    pmkidExposed: false,
    rogue: false,
  },
  {
    ssid: "Ring-4A2C",
    bssid: "18:B4:30:4A:2C:10",
    vendor: "Amazon",
    band: "2.4",
    channel: 11,
    widthMhz: 20,
    encryption: "WPA2-PSK",
    cipher: "CCMP",
    akm: "00-0F-AC:02 (PSK)",
    pmf: "off",
    wps: false,
    hidden: false,
    txPowerDbm: 11,
    position: { x: 40, y: 62 },
    role: "iot-neighbor",
    notes: "Camera AP with vendor-default style PSK.",
    psk: "ring12345",
    pmkidExposed: true,
    rogue: false,
  },
  {
    ssid: "Tesla-123",
    bssid: "98:ED:5C:12:30:01",
    vendor: "Tesla",
    band: "2.4",
    channel: 6,
    widthMhz: 20,
    encryption: "WPA2-PSK",
    cipher: "CCMP",
    akm: "00-0F-AC:02 (PSK)",
    pmf: "required",
    wps: false,
    hidden: false,
    txPowerDbm: 13,
    position: { x: 78, y: 70 },
    role: "vehicle",
    notes: "Vehicle AP. High-entropy provisioning PSK.",
    psk: "Xv9!qL4#nR8w",
    pmkidExposed: false,
    rogue: false,
  },
  {
    ssid: "Cafe-WiFi",
    bssid: "B0:B2:DC:55:09:03",
    vendor: "Ubiquiti",
    band: "2.4",
    channel: 1,
    widthMhz: 20,
    encryption: "OPEN",
    cipher: "none",
    akm: "none",
    pmf: "off",
    wps: false,
    hidden: false,
    txPowerDbm: 16,
    position: { x: 22, y: 74 },
    role: "neighbor",
    notes: "Open cafe hotspot.",
    pmkidExposed: false,
    rogue: false,
  },
  {
    ssid: "ATT-WIFI-6E2A",
    bssid: "20:3D:66:6E:2A:10",
    vendor: "Arris",
    band: "5",
    channel: 149,
    widthMhz: 80,
    encryption: "WPA2-PSK",
    cipher: "CCMP",
    akm: "00-0F-AC:02 (PSK)",
    pmf: "optional",
    wps: true,
    hidden: false,
    txPowerDbm: 20,
    position: { x: 112, y: 12 },
    role: "neighbor",
    notes: "Residential gateway, WPS on.",
    psk: "kT8mN2pQ9sW4",
    pmkidExposed: true,
    rogue: false,
  },
];

export const LAB_STAS: StaTemplate[] = [
  {
    mac: "3C:22:FB:10:44:01",
    manufacturer: "Apple",
    associatedBssid: "00:1A:8C:10:00:01",
    probes: ["Hopper-Corp"],
    position: { x: 56, y: 26 },
  },
  {
    mac: "DA:4A:91:02:11:88",
    manufacturer: "Apple (randomized)",
    associatedBssid: "00:1A:8C:10:00:01",
    probes: ["Hopper-Corp", "Hopper-Guest"],
    position: { x: 70, y: 30 },
  },
  {
    mac: "8C:85:90:77:02:13",
    manufacturer: "Apple",
    associatedBssid: "00:1A:8C:10:00:10",
    probes: ["Hopper-Guest"],
    position: { x: 46, y: 52 },
  },
  {
    mac: "F2:C1:3A:90:00:21",
    manufacturer: "Samsung (randomized)",
    associatedBssid: "00:1A:8C:10:00:11",
    probes: ["Hopper-Guest", "xfinitywifi"],
    position: { x: 52, y: 46 },
  },
  {
    mac: "00:1A:8C:99:00:05",
    manufacturer: "Hopper Networks",
    associatedBssid: "00:1A:8C:10:00:40",
    probes: ["Hopper-Mgmt"],
    position: { x: 61, y: 17 },
  },
  {
    mac: "B8:27:EB:44:10:02",
    manufacturer: "Raspberry Pi",
    associatedBssid: "00:1A:8C:10:00:20",
    probes: ["Hopper-IoT"],
    position: { x: 90, y: 20 },
  },
  {
    mac: "00:04:13:22:10:08",
    manufacturer: "Snom",
    associatedBssid: "00:1A:8C:10:00:30",
    probes: ["Hopper-Voice"],
    position: { x: 28, y: 20 },
  },
  {
    mac: "E2:19:44:00:81:12",
    manufacturer: "Google (randomized)",
    associatedBssid: null,
    probes: ["Hopper-Corp", "Hopper-Guest", "CivicFree"],
    position: { x: 60, y: 40 },
  },
  {
    mac: "00:1B:A9:77:02:20",
    manufacturer: "Brother",
    associatedBssid: "00:1B:A9:77:02:19",
    probes: ["Printer-Setup"],
    position: { x: 73, y: 29 },
  },
  {
    mac: "C8:3A:35:10:22:09",
    manufacturer: "Tenda",
    associatedBssid: "DE:AD:BE:EF:10:01",
    probes: ["Hopper-Corp"],
    position: { x: 65, y: 54 },
  },
  {
    mac: "A4:83:E7:11:00:32",
    manufacturer: "Apple",
    associatedBssid: "A0:04:60:1B:33:70",
    probes: ["NETGEAR70"],
    position: { x: 20, y: 42 },
  },
  {
    mac: "F6:12:90:44:01:55",
    manufacturer: "Unknown (randomized)",
    associatedBssid: null,
    probes: ["Marriott_Guest", "Cafe-WiFi"],
    position: { x: 14, y: 12 },
  },
];

export const LAB_SCOPE_SSIDS = ["Hopper-*", "Printer-Setup"];
export const LAB_SCOPE_BSSIDS = ["00:1A:8C:*", "DE:AD:BE:EF:10:01", "00:1B:A9:77:02:19"];

export function instantiateAps(): AccessPoint[] {
  return LAB_APS.map((t, i) => ({
    id: `ap-${i}`,
    ssid: t.ssid,
    bssid: t.bssid,
    vendor: t.vendor,
    band: t.band,
    channel: t.channel,
    widthMhz: t.widthMhz,
    encryption: t.encryption,
    cipher: t.cipher,
    akm: t.akm,
    pmf: t.pmf,
    wps: t.wps,
    hidden: t.hidden,
    revealedSsid: !t.hidden,
    txPowerDbm: t.txPowerDbm,
    position: { ...t.position },
    role: t.role,
    notes: t.notes,
    psk: t.psk,
    beaconIntervalMs: 102,
    lastSeen: 0,
    rssi: -100,
    noise: -95,
    snr: 0,
    packetCount: 0,
    clientCount: 0,
    pmkidExposed: t.pmkidExposed,
    rogue: t.rogue,
    inScope: false,
    risk: 0,
    riskReasons: [],
  }));
}

export function instantiateStas(): Station[] {
  return LAB_STAS.map((t, i) => ({
    id: `sta-${i}`,
    mac: t.mac,
    randomized: (Number.parseInt(t.mac.slice(0, 2), 16) & 0x02) !== 0,
    manufacturer: t.manufacturer,
    associatedBssid: t.associatedBssid,
    probes: [...t.probes],
    position: { ...t.position },
    lastSeen: 0,
    rssi: -90,
    seq: (i * 17) & 0xfff,
  }));
}

export const CHANNELS: Record<Band, number[]> = {
  "2.4": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
  "5": [36, 40, 44, 48, 149, 153, 157, 161, 165],
  "6": [37, 53, 69, 85, 101],
};
