"""
Centralized constants for the James agent system.
"""

# SEDGE (Self-Evolving Decision Graph Engine) Constants
SEDGE_EPSILON = 1e-6
OUTCOME_SUCCESS = "SUCCESS"
OUTCOME_FAILURE = "FAILURE"
OUTCOME_PARTIAL = "PARTIAL_SIGNAL"
STATE_START = "START"

# SEDGE Parrot WiFi System Domains
STATE_NETWORK_DISCOVERY = "NETWORK_DISCOVERY"
STATE_TARGET_ANALYSIS = "TARGET_ANALYSIS"
STATE_SECURITY_PROFILING = "SECURITY_PROFILING"

ACTION_PASSIVE_SCAN = "PASSIVE_SCAN"
ACTION_HANDSHAKE_CAPTURE = "HANDSHAKE_CAPTURE"
ACTION_DEAUTH_TEST = "DEAUTH_TEST"
ACTION_EVIL_TWIN_SIMULATION = "EVIL_TWIN_SIMULATION"
